<a href="https://colab.research.google.com/github/Cdenlz/Aprendizaje-Automatico-Luffi/blob/Clase-1/Ejercicios_Act_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.zeros((10,), dtype=int)
print(f'Este es el array "a":',a)

Este es el array "a": [0 0 0 0 0 0 0 0 0 0]


In [ ]:
np.array([range(1,21)])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]])

In [ ]:
a=np.array([range(2,51,2)])
print(a)

[[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
  50]]


In [ ]:
np.random.seed(2)
np.random.rand(4,4)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# Tu código aquí
c=a+b
print(c)

[5 7 9]


In [ ]:
a=np.random.randint(1,11,(3,3))
b=np.random.randint(1,11,(3,3))

c=a*b
print('Matriz A \n', a)
print('Matriz B \n', b)
print('Resultado Multiplicacion \n',c)

Matriz A 
 [[ 2  4  6]
 [ 9  5  7]
 [ 4 10  3]]
Matriz B 
 [[ 1  5  3]
 [ 5  2  8]
 [ 9  3 10]]
Resultado Multiplicacion 
 [[ 2 20 18]
 [45 10 56]
 [36 30 30]]


In [ ]:
valor=np.random.randint(1,101,(15))

valormax=np.max(valor)
valormin=np.min(valor)
valorpro=np.average(valor)
print('Los valores son:',valor)
print('El valor maximo es:',valormax)
print('El valor minimo es:',valormin)
print('El valor promedio es:',valorpro)

Los valores son: [ 9 18 23 74 58 91 63 84 97 44 33 27  9 77 11]
El valor maximo es: 97
El valor minimo es: 9
El valor promedio es: 47.86666666666667


In [ ]:
matriz=np.arange(1,26).reshape(5,5)
print(matriz)

diagonal=np.diag(matriz)
print('La diagonal esta compuesta por:',diagonal)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
La diagonal esta compuesta por: [ 1  7 13 19 25]


In [ ]:
matriz=np.random.randint(1,21,(5,5))
print(matriz)

sumafila=np.sum(matriz , axis=1)
print('La suma de las filas:',sumafila)
sumacol=np.sum(matriz , axis=0)
print('La suma de las columnas:',sumacol)


[[ 9  3 10  6  7]
 [ 7 20 19  2  5]
 [ 9 18  7  6  2]
 [19 12  6 11  9]
 [ 4  1 17 12 17]]
La suma de las filas: [35 53 42 57 51]
La suma de las columnas: [48 54 59 37 40]
